In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
mymatrix = np.array(mylist)

In [13]:
mymatrix.shape

(3, 3)

In [16]:
mynewmatrix = np.array(mylist)

In [17]:
mynewmatrix.shape

(3, 3)

In [22]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones((5,5)) * 2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [32]:
np.ones(4) + 10

array([11., 11., 11., 11.])

In [37]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.random.rand(1)

array([0.30173713])

In [42]:
np.random.rand(5)

array([0.13221214, 0.18554753, 0.95207213, 0.36029985, 0.61576044])

In [43]:
np.random.rand(5,5)

array([[0.30595201, 0.81588262, 0.13621128, 0.48390876, 0.0437784 ],
       [0.19682596, 0.46457423, 0.99619381, 0.56576287, 0.19409789],
       [0.71087184, 0.09114862, 0.3383124 , 0.08418238, 0.86943287],
       [0.58152159, 0.01719455, 0.3964263 , 0.10207938, 0.97974279],
       [0.29606593, 0.08134955, 0.72597634, 0.13246363, 0.27588018]])

In [46]:
np.random.randn(10) # standard normal deviation -1 to 1

array([-0.18734068,  1.44504242,  1.08701882,  0.71329984, -0.80922094,
       -0.29438723,  1.20906896,  0.39868384,  1.22170386, -0.58088702])

In [49]:
# np.random.normal

In [51]:
np.random.randint(1, 100, 10) # return 10 random number from 1 to 100

array([39, 63,  5, 50, 11, 49, 81, 50, 13, 62])

In [60]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [62]:
arr = np.arange(25)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [64]:
ranarr = np.random.randint(0, 50, 10)

In [65]:
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [67]:
arr.reshape(5,5) #array.reshape(a, b) a*b>=arr.size

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
ranarr.max()

48

In [70]:
ranarr.min()

10

In [71]:
ranarr.argmax()

1

In [72]:
ranarr.argmin()

6

In [73]:
ranarr.dtype

dtype('int64')

In [78]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr34 = arr.reshape(3,4)
arr34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12])

ValueError: cannot reshape array of size 11 into shape (3,4)